class PlayerBioSeed {
  static final Map<String, PlayerBio> biosByName = {
    'aaron gordon': PlayerBio(
      displayName: 'Aaron Gordon',
      jerseyNumber: '32',
      heightCm: 203.2,
      weightKg: 106.6,
      country: 'USA',
      previousTeam: 'Arizona',
      birthDate: DateTime(1995, 9, 16),
      experienceYears: 11,
    ),
    'aaron nesmith': PlayerBio(
      displayName: 'Aaron Nesmith',
      jerseyNumber: '23',
      heightCm: 198.1,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'Vanderbilt',
      birthDate: DateTime(1999, 10, 16),
      experienceYears: 5,
    ),
    'aaron wiggins': PlayerBio(
      displayName: 'Aaron Wiggins',
      jerseyNumber: '21',
      heightCm: 195.6,
      weightKg: 86.2,
      country: 'USA',
      previousTeam: 'Maryland',
      birthDate: DateTime(1999, 1, 2),
      experienceYears: 4,
    ),
    'ace bailey': PlayerBio(
      displayName: 'Ace Bailey',
      jerseyNumber: '19',
      heightCm: 200.7,
      weightKg: 90.7,
      country: 'USA',
      previousTeam: 'Rutgers',
      birthDate: DateTime(2006, 8, 13),
      experienceYears: 0,
    ),
    'aj green': PlayerBio(
      displayName: 'AJ Green',
      jerseyNumber: '20',
      heightCm: 193,
      weightKg: 86.2,
      country: 'USA',
      previousTeam: 'Northern Iowa',
      birthDate: DateTime(1999, 9, 27),
      experienceYears: 3,
    ),
    'al horford': PlayerBio(
      displayName: 'Al Horford',
      jerseyNumber: '42',
      heightCm: 205.7,
      weightKg: 108.9,
      country: 'Dominican Republic',
      previousTeam: 'Florida',
      birthDate: DateTime(1986, 6, 3),
      experienceYears: 18,
    ),
    'alex caruso': PlayerBio(
      displayName: 'Alex Caruso',
      jerseyNumber: '9',
      heightCm: 195.6,
      weightKg: 84.4,
      country: 'USA',
      previousTeam: 'Texas A\u0026M',
      birthDate: DateTime(1994, 2, 28),
      experienceYears: 8,
    ),
    'alex sarr': PlayerBio(
      displayName: 'Alex Sarr',
      jerseyNumber: '20',
      heightCm: 213.4,
      weightKg: 93,
      country: 'France',
      previousTeam: 'Washington Wizards',
      birthDate: DateTime(2005, 4, 26),
      experienceYears: 1,
    ),
    'alperen sengun': PlayerBio(
      displayName: 'Alperen Sengun',
      jerseyNumber: '28',
      heightCm: 210.8,
      weightKg: 110.2,
      country: 'Turkey',
      previousTeam: 'Besiktas',
      birthDate: DateTime(2002, 7, 25),
      experienceYears: 4,
    ),
    'amen thompson': PlayerBio(
      displayName: 'Amen Thompson',
      jerseyNumber: '1',
      heightCm: 200.7,
      weightKg: 90.7,
      country: 'USA',
      previousTeam: 'Overtime Elite',
      birthDate: DateTime(2003, 1, 30),
      experienceYears: 2,
    ),
    'andre drummond': PlayerBio(
      displayName: 'Andre Drummond',
      jerseyNumber: '1',
      heightCm: 210.8,
      weightKg: 126.6,
      country: 'USA',
      previousTeam: 'Connecticut',
      birthDate: DateTime(1993, 8, 10),
      experienceYears: 13,
    ),
    'andrew nembhard': PlayerBio(
      displayName: 'Andrew Nembhard',
      jerseyNumber: '2',
      heightCm: 193,
      weightKg: 86.6,
      country: 'Canada',
      previousTeam: 'Gonzaga',
      birthDate: DateTime(2000, 1, 16),
      experienceYears: 3,
    ),
    'andrew wiggins': PlayerBio(
      displayName: 'Andrew Wiggins',
      jerseyNumber: '22',
      heightCm: 200.7,
      weightKg: 89.4,
      country: 'Canada',
      previousTeam: 'Kansas',
      birthDate: DateTime(1995, 2, 23),
      experienceYears: 11,
    ),
    'anfernee simons': PlayerBio(
      displayName: 'Anfernee Simons',
      jerseyNumber: '1',
      heightCm: 190.5,
      weightKg: 90.7,
      country: 'USA',
      previousTeam: 'Edgewater HS (FL)',
      birthDate: DateTime(1999, 6, 8),
      experienceYears: 7,
    ),
    'anthony black': PlayerBio(
      displayName: 'Anthony Black',
      jerseyNumber: '0',
      heightCm: 200.7,
      weightKg: 90.7,
      country: 'USA',
      previousTeam: 'Arkansas',
      birthDate: DateTime(2004, 1, 20),
      experienceYears: 2,
    ),
    'anthony davis': PlayerBio(
      displayName: 'Anthony Davis',
      jerseyNumber: '3',
      heightCm: 208.3,
      weightKg: 114.8,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(1993, 3, 11),
      experienceYears: 13,
    ),
    'anthony edwards': PlayerBio(
      displayName: 'Anthony Edwards',
      jerseyNumber: '5',
      heightCm: 193,
      weightKg: 102.1,
      country: 'USA',
      previousTeam: 'Georgia',
      birthDate: DateTime(2001, 8, 5),
      experienceYears: 5,
    ),
    'ausar thompson': PlayerBio(
      displayName: 'Ausar Thompson',
      jerseyNumber: '9',
      heightCm: 198.1,
      weightKg: 93,
      country: 'USA',
      previousTeam: 'Overtime Elite',
      birthDate: DateTime(2003, 1, 30),
      experienceYears: 2,
    ),
    'austin reaves': PlayerBio(
      displayName: 'Austin Reaves',
      jerseyNumber: '15',
      heightCm: 195.6,
      weightKg: 89.4,
      country: 'USA',
      previousTeam: 'Oklahoma',
      birthDate: DateTime(1998, 5, 29),
      experienceYears: 4,
    ),
    'ayo dosunmu': PlayerBio(
      displayName: 'Ayo Dosunmu',
      jerseyNumber: '11',
      heightCm: 195.6,
      weightKg: 90.7,
      country: 'USA',
      previousTeam: 'Illinois',
      birthDate: DateTime(2000, 1, 17),
      experienceYears: 4,
    ),
    'bam adebayo': PlayerBio(
      displayName: 'Bam Adebayo',
      jerseyNumber: '13',
      heightCm: 205.7,
      weightKg: 115.7,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(1997, 7, 18),
      experienceYears: 8,
    ),
    'bennedict mathurin': PlayerBio(
      displayName: 'Bennedict Mathurin',
      jerseyNumber: '00',
      heightCm: 195.6,
      weightKg: 95.3,
      country: 'Canada',
      previousTeam: 'Arizona',
      birthDate: DateTime(2002, 6, 19),
      experienceYears: 3,
    ),
    'bilal coulibaly': PlayerBio(
      displayName: 'Bilal Coulibaly',
      jerseyNumber: '0',
      heightCm: 203.2,
      weightKg: 88.5,
      country: 'France',
      previousTeam: 'Metropolitans 92',
      birthDate: DateTime(2004, 7, 26),
      experienceYears: 2,
    ),
    'bobby portis': PlayerBio(
      displayName: 'Bobby Portis',
      jerseyNumber: '9',
      heightCm: 208.3,
      weightKg: 113.4,
      country: 'USA',
      previousTeam: 'Arkansas',
      birthDate: DateTime(1995, 2, 10),
      experienceYears: 10,
    ),
    'bogdan bogdanovic': PlayerBio(
      displayName: 'Bogdan Bogdanovic',
      jerseyNumber: '10',
      heightCm: 196,
      weightKg: 102,
      country: 'Serbia',
      previousTeam: 'Partizan',
      birthDate: DateTime(1992, 8, 18),
      experienceYears: 8,
    ),
    'bradley beal': PlayerBio(
      displayName: 'Bradley Beal',
      jerseyNumber: '3',
      heightCm: 193,
      weightKg: 93.9,
      country: 'USA',
      previousTeam: 'Florida',
      birthDate: DateTime(1993, 6, 28),
      experienceYears: 13,
    ),
    'brandin podziemski': PlayerBio(
      displayName: 'Brandin Podziemski',
      jerseyNumber: '2',
      heightCm: 193,
      weightKg: 93,
      country: 'USA',
      previousTeam: 'Santa Clara',
      birthDate: DateTime(2003, 2, 25),
      experienceYears: 2,
    ),
    'brandon clarke': PlayerBio(
      displayName: 'Brandon Clarke',
      jerseyNumber: '15',
      heightCm: 203.2,
      weightKg: 97.5,
      country: 'Canada',
      previousTeam: 'Gonzaga',
      birthDate: DateTime(1996, 9, 19),
      experienceYears: 6,
    ),
    'brandon ingram': PlayerBio(
      displayName: 'Brandon Ingram',
      jerseyNumber: '3',
      heightCm: 203.2,
      weightKg: 86.2,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(1997, 9, 2),
      experienceYears: 9,
    ),
    'brandon miller': PlayerBio(
      displayName: 'Brandon Miller',
      jerseyNumber: '24',
      heightCm: 200.7,
      weightKg: 90.7,
      country: 'USA',
      previousTeam: 'Alabama',
      birthDate: DateTime(2002, 11, 22),
      experienceYears: 2,
    ),
    'brice sensabaugh': PlayerBio(
      displayName: 'Brice Sensabaugh',
      jerseyNumber: '28',
      heightCm: 195.6,
      weightKg: 106.6,
      country: 'USA',
      previousTeam: 'Ohio State',
      birthDate: DateTime(2003, 10, 30),
      experienceYears: 2,
    ),
    'brook lopez': PlayerBio(
      displayName: 'Brook Lopez',
      jerseyNumber: '11',
      heightCm: 215.9,
      weightKg: 127.9,
      country: 'USA',
      previousTeam: 'Stanford',
      birthDate: DateTime(1988, 4, 1),
      experienceYears: 17,
    ),
    'bub carrington': PlayerBio(
      displayName: 'Bub Carrington',
      jerseyNumber: '7',
      heightCm: 193,
      weightKg: 86.2,
      country: 'USA',
      previousTeam: 'Pittsburgh',
      birthDate: DateTime(2005, 7, 21),
      experienceYears: 1,
    ),
    'buddy hield': PlayerBio(
      displayName: 'Buddy Hield',
      jerseyNumber: '7',
      heightCm: 193,
      weightKg: 99.8,
      country: 'Bahamas',
      previousTeam: 'Oklahoma',
      birthDate: DateTime(1992, 12, 17),
      experienceYears: 9,
    ),
    'cade cunningham': PlayerBio(
      displayName: 'Cade Cunningham',
      jerseyNumber: '2',
      heightCm: 198.1,
      weightKg: 99.8,
      country: 'USA',
      previousTeam: 'Oklahoma State',
      birthDate: DateTime(2001, 9, 25),
      experienceYears: 4,
    ),
    'cam johnson': PlayerBio(
      displayName: 'Cameron Johnson',
      jerseyNumber: '23',
      heightCm: 203.2,
      weightKg: 95.3,
      country: 'USA',
      previousTeam: 'North Carolina',
      birthDate: DateTime(1996, 3, 3),
      experienceYears: 6,
    ),
    'cam thomas': PlayerBio(
      displayName: 'Cam Thomas',
      jerseyNumber: '24',
      heightCm: 190.5,
      weightKg: 95.3,
      country: 'Japan',
      previousTeam: 'Louisiana State',
      birthDate: DateTime(2001, 10, 13),
      experienceYears: 4,
    ),
    'cason wallace': PlayerBio(
      displayName: 'Cason Wallace',
      jerseyNumber: '22',
      heightCm: 190.5,
      weightKg: 88.5,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(2003, 11, 7),
      experienceYears: 2,
    ),
    'chet holmgren': PlayerBio(
      displayName: 'Chet Holmgren',
      jerseyNumber: '7',
      heightCm: 215.9,
      weightKg: 94.3,
      country: 'USA',
      previousTeam: 'Gonzaga',
      birthDate: DateTime(2002, 5, 1),
      experienceYears: 2,
    ),
    'christian braun': PlayerBio(
      displayName: 'Christian Braun',
      jerseyNumber: '0',
      heightCm: 198.1,
      weightKg: 99.8,
      country: 'USA',
      previousTeam: 'Kansas',
      birthDate: DateTime(2001, 4, 17),
      experienceYears: 3,
    ),
    'cj mccollum': PlayerBio(
      displayName: 'CJ McCollum',
      jerseyNumber: '3',
      heightCm: 190.5,
      weightKg: 86.2,
      country: 'USA',
      previousTeam: 'Lehigh',
      birthDate: DateTime(1991, 9, 19),
      experienceYears: 12,
    ),
    'coby white': PlayerBio(
      displayName: 'Coby White',
      jerseyNumber: '0',
      heightCm: 195.6,
      weightKg: 88.5,
      country: 'USA',
      previousTeam: 'North Carolina',
      birthDate: DateTime(2000, 2, 16),
      experienceYears: 6,
    ),
    'cole anthony': PlayerBio(
      displayName: 'Cole Anthony',
      jerseyNumber: '25',
      heightCm: 188,
      weightKg: 83.9,
      country: 'USA',
      previousTeam: 'North Carolina',
      birthDate: DateTime(2000, 5, 15),
      experienceYears: 5,
    ),
    'cooper flagg': PlayerBio(
      displayName: 'Cooper Flagg',
      jerseyNumber: '32',
      heightCm: 203.2,
      weightKg: 93,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(2006, 12, 21),
      experienceYears: 0,
    ),
    'corey kispert': PlayerBio(
      displayName: 'Corey Kispert',
      jerseyNumber: '24',
      heightCm: 198.1,
      weightKg: 101.6,
      country: 'USA',
      previousTeam: 'Gonzaga',
      birthDate: DateTime(1999, 3, 3),
      experienceYears: 4,
    ),
    'daniel gafford': PlayerBio(
      displayName: 'Daniel Gafford',
      jerseyNumber: '21',
      heightCm: 208.3,
      weightKg: 120.2,
      country: 'USA',
      previousTeam: 'Arkansas',
      birthDate: DateTime(1998, 10, 1),
      experienceYears: 6,
    ),
    'dariq whitehead': PlayerBio(
      displayName: 'Dariq Whitehead',
      jerseyNumber: '0',
      heightCm: 198.1,
      weightKg: 99.8,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(2004, 8, 1),
      experienceYears: 2,
    ),
    'darius garland': PlayerBio(
      displayName: 'Darius Garland',
      jerseyNumber: '10',
      heightCm: 185.4,
      weightKg: 87.1,
      country: 'USA',
      previousTeam: 'Vanderbilt',
      birthDate: DateTime(2000, 1, 26),
      experienceYears: 6,
    ),
    'davion mitchell': PlayerBio(
      displayName: 'Davion Mitchell',
      jerseyNumber: '45',
      heightCm: 182.9,
      weightKg: 91.6,
      country: 'USA',
      previousTeam: 'Baylor',
      birthDate: DateTime(1998, 9, 5),
      experienceYears: 4,
    ),
    'dayron sharpe': PlayerBio(
      displayName: 'DayRon Sharpe',
      jerseyNumber: '20',
      heightCm: 206,
      weightKg: 120,
      country: 'USA',
      previousTeam: 'North Carolina',
      birthDate: DateTime(2001, 11, 6),
      experienceYears: 4,
    ),
    'deaaron fox': PlayerBio(
      displayName: 'DeAaron Fox',
      jerseyNumber: '4',
      heightCm: 191,
      weightKg: 84,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(1997, 12, 20),
      experienceYears: 8,
    ),
    'dean wade': PlayerBio(
      displayName: 'Dean Wade',
      jerseyNumber: '32',
      heightCm: 205.7,
      weightKg: 103.4,
      country: 'USA',
      previousTeam: 'Kansas State',
      birthDate: DateTime(1996, 11, 20),
      experienceYears: 6,
    ),
    'deandre ayton': PlayerBio(
      displayName: 'Deandre Ayton',
      jerseyNumber: '5',
      heightCm: 213.4,
      weightKg: 114.3,
      country: 'Bahamas',
      previousTeam: 'Arizona',
      birthDate: DateTime(1998, 7, 23),
      experienceYears: 7,
    ),
    'deandre hunter': PlayerBio(
      displayName: 'DeAndre Hunter',
      jerseyNumber: '12',
      heightCm: 203,
      weightKg: 100,
      country: 'USA',
      previousTeam: 'Virginia',
      birthDate: DateTime(1997, 12, 2),
      experienceYears: 6,
    ),
    'dejounte murray': PlayerBio(
      displayName: 'Dejounte Murray',
      jerseyNumber: '5',
      heightCm: 193,
      weightKg: 81.6,
      country: 'USA',
      previousTeam: 'Washington',
      birthDate: DateTime(1996, 9, 19),
      experienceYears: 9,
    ),
    'demar derozan': PlayerBio(
      displayName: 'DeMar DeRozan',
      jerseyNumber: '10',
      heightCm: 198.1,
      weightKg: 99.8,
      country: 'USA',
      previousTeam: 'Southern California',
      birthDate: DateTime(1989, 8, 7),
      experienceYears: 16,
    ),
    'deni avdija': PlayerBio(
      displayName: 'Deni Avdija',
      jerseyNumber: '8',
      heightCm: 205.7,
      weightKg: 108.9,
      country: 'Israel',
      previousTeam: 'Maccabi Tel Aviv',
      birthDate: DateTime(2001, 1, 3),
      experienceYears: 5,
    ),
    'dereck lively ii': PlayerBio(
      displayName: 'Dereck Lively II',
      jerseyNumber: '2',
      heightCm: 215.9,
      weightKg: 104.3,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(2004, 2, 12),
      experienceYears: 2,
    ),
    'derrick jones jr': PlayerBio(
      displayName: 'Derrick Jones Jr.',
      jerseyNumber: '5',
      heightCm: 198.1,
      weightKg: 95.3,
      country: 'USA',
      previousTeam: 'UNLV',
      birthDate: DateTime(1997, 2, 15),
      experienceYears: 9,
    ),
    'derrick white': PlayerBio(
      displayName: 'Derrick White',
      jerseyNumber: '9',
      heightCm: 193,
      weightKg: 86.2,
      country: 'USA',
      previousTeam: 'Colorado',
      birthDate: DateTime(1994, 7, 2),
      experienceYears: 8,
    ),
    'desmond bane': PlayerBio(
      displayName: 'Desmond Bane',
      jerseyNumber: '3',
      heightCm: 195.6,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'TCU',
      birthDate: DateTime(1998, 6, 25),
      experienceYears: 5,
    ),
    'devin booker': PlayerBio(
      displayName: 'Devin Booker',
      jerseyNumber: '1',
      heightCm: 198.1,
      weightKg: 93.4,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(1996, 10, 30),
      experienceYears: 10,
    ),
    'devin vassell': PlayerBio(
      displayName: 'Devin Vassell',
      jerseyNumber: '24',
      heightCm: 195.6,
      weightKg: 90.7,
      country: 'USA',
      previousTeam: 'Florida State',
      birthDate: DateTime(2000, 8, 23),
      experienceYears: 5,
    ),
    'dillon brooks': PlayerBio(
      displayName: 'Dillon Brooks',
      jerseyNumber: '9',
      heightCm: 198.1,
      weightKg: 102.1,
      country: 'Canada',
      previousTeam: 'Oregon',
      birthDate: DateTime(1996, 1, 22),
      experienceYears: 8,
    ),
    'domantas sabonis': PlayerBio(
      displayName: 'Domantas Sabonis',
      jerseyNumber: '11',
      heightCm: 208.3,
      weightKg: 108.9,
      country: 'Lithuania',
      previousTeam: 'Gonzaga',
      birthDate: DateTime(1996, 5, 3),
      experienceYears: 9,
    ),
    'donovan clingan': PlayerBio(
      displayName: 'Donovan Clingan',
      jerseyNumber: '23',
      heightCm: 218.4,
      weightKg: 127,
      country: 'USA',
      previousTeam: 'Connecticut',
      birthDate: DateTime(2004, 2, 23),
      experienceYears: 1,
    ),
    'donovan mitchell': PlayerBio(
      displayName: 'Donovan Mitchell',
      jerseyNumber: '45',
      heightCm: 190.5,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'Louisville',
      birthDate: DateTime(1996, 9, 7),
      experienceYears: 8,
    ),
    'donte divincenzo': PlayerBio(
      displayName: 'Donte DiVincenzo',
      jerseyNumber: '0',
      heightCm: 193,
      weightKg: 92.1,
      country: 'USA',
      previousTeam: 'Villanova',
      birthDate: DateTime(1997, 1, 31),
      experienceYears: 7,
    ),
    'draymond green': PlayerBio(
      displayName: 'Draymond Green',
      jerseyNumber: '23',
      heightCm: 198.1,
      weightKg: 104.3,
      country: 'USA',
      previousTeam: 'Michigan State',
      birthDate: DateTime(1990, 3, 4),
      experienceYears: 13,
    ),
    'duncan robinson': PlayerBio(
      displayName: 'Duncan Robinson',
      jerseyNumber: '55',
      heightCm: 200.7,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'Michigan',
      birthDate: DateTime(1994, 4, 22),
      experienceYears: 7,
    ),
    'dyson daniels': PlayerBio(
      displayName: 'Dyson Daniels',
      jerseyNumber: '5',
      heightCm: 200.7,
      weightKg: 90.3,
      country: 'Australia',
      previousTeam: 'NBA G League Ignite',
      birthDate: DateTime(2003, 3, 17),
      experienceYears: 3,
    ),
    'egor demin': PlayerBio(
      displayName: 'Egor Demin',
      heightCm: 206,
      weightKg: 86,
      country: 'Russia',
      previousTeam: 'BYU',
      birthDate: DateTime(2006, 3, 3),
      experienceYears: 0,
    ),
    'evan mobley': PlayerBio(
      displayName: 'Evan Mobley',
      jerseyNumber: '4',
      heightCm: 210.8,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'Southern California',
      birthDate: DateTime(2001, 6, 18),
      experienceYears: 4,
    ),
    'franz wagner': PlayerBio(
      displayName: 'Franz Wagner',
      jerseyNumber: '22',
      heightCm: 208.3,
      weightKg: 99.8,
      country: 'Germany',
      previousTeam: 'Michigan',
      birthDate: DateTime(2001, 8, 27),
      experienceYears: 4,
    ),
    'fred vanvleet': PlayerBio(
      displayName: 'Fred VanVleet',
      jerseyNumber: '5',
      heightCm: 182.9,
      weightKg: 89.4,
      country: 'USA',
      previousTeam: 'Wichita State',
      birthDate: DateTime(1994, 2, 25),
      experienceYears: 9,
    ),
    'gabe vincent': PlayerBio(
      displayName: 'Gabe Vincent',
      jerseyNumber: '7',
      heightCm: 188,
      weightKg: 90.7,
      country: 'USA',
      previousTeam: 'California-Santa Barbara',
      birthDate: DateTime(1996, 6, 14),
      experienceYears: 6,
    ),
    'gary trent jr': PlayerBio(
      displayName: 'Gary Trent Jr.',
      jerseyNumber: '5',
      heightCm: 195.6,
      weightKg: 92.5,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(1999, 1, 18),
      experienceYears: 7,
    ),
    'giannis antetokounmpo': PlayerBio(
      displayName: 'Giannis Antetokounmpo',
      jerseyNumber: '34',
      heightCm: 210.8,
      weightKg: 110.2,
      country: 'Greece',
      previousTeam: 'Filathlitikos',
      birthDate: DateTime(1994, 12, 6),
      experienceYears: 12,
    ),
    'gradey dick': PlayerBio(
      displayName: 'Gradey Dick',
      jerseyNumber: '1',
      heightCm: 198.1,
      weightKg: 90.7,
      country: 'USA',
      previousTeam: 'Kansas',
      birthDate: DateTime(2003, 11, 20),
      experienceYears: 2,
    ),
    'grant williams': PlayerBio(
      displayName: 'Grant Williams',
      jerseyNumber: '2',
      heightCm: 198.1,
      weightKg: 107,
      country: 'USA',
      previousTeam: 'Tennessee',
      birthDate: DateTime(1998, 11, 30),
      experienceYears: 6,
    ),
    'grayson allen': PlayerBio(
      displayName: 'Grayson Allen',
      jerseyNumber: '8',
      heightCm: 193,
      weightKg: 89.8,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(1995, 10, 8),
      experienceYears: 7,
    ),
    'harrison barnes': PlayerBio(
      displayName: 'Harrison Barnes',
      jerseyNumber: '40',
      heightCm: 203.2,
      weightKg: 102.1,
      country: 'USA',
      previousTeam: 'North Carolina',
      birthDate: DateTime(1992, 5, 30),
      experienceYears: 13,
    ),
    'herbert jones': PlayerBio(
      displayName: 'Herbert Jones',
      jerseyNumber: '2',
      heightCm: 200.7,
      weightKg: 93.4,
      country: 'USA',
      previousTeam: 'Alabama',
      birthDate: DateTime(1998, 10, 6),
      experienceYears: 4,
    ),
    'immanuel quickley': PlayerBio(
      displayName: 'Immanuel Quickley',
      jerseyNumber: '5',
      heightCm: 188,
      weightKg: 86.2,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(1999, 6, 17),
      experienceYears: 5,
    ),
    'isaac okoro': PlayerBio(
      displayName: 'Isaac Okoro',
      jerseyNumber: '35',
      heightCm: 195.6,
      weightKg: 102.1,
      country: 'USA',
      previousTeam: 'Auburn',
      birthDate: DateTime(2001, 1, 26),
      experienceYears: 5,
    ),
    'isaiah collier': PlayerBio(
      displayName: 'Isaiah Collier',
      jerseyNumber: '8',
      heightCm: 190.5,
      weightKg: 95.3,
      country: 'USA',
      previousTeam: 'Southern California',
      birthDate: DateTime(2004, 10, 8),
      experienceYears: 1,
    ),
    'isaiah hartenstein': PlayerBio(
      displayName: 'Isaiah Hartenstein',
      jerseyNumber: '55',
      heightCm: 213.4,
      weightKg: 113.4,
      country: 'Germany',
      previousTeam: 'Zalgiris',
      birthDate: DateTime(1998, 5, 5),
      experienceYears: 7,
    ),
    'isaiah jackson': PlayerBio(
      displayName: 'Isaiah Jackson',
      jerseyNumber: '22',
      heightCm: 205.7,
      weightKg: 93,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(2002, 1, 10),
      experienceYears: 4,
    ),
    'isaiah stewart': PlayerBio(
      displayName: 'Isaiah Stewart',
      jerseyNumber: '28',
      heightCm: 203.2,
      weightKg: 113.4,
      country: 'USA',
      previousTeam: 'Washington',
      birthDate: DateTime(2001, 5, 22),
      experienceYears: 5,
    ),
    'ivica zubac': PlayerBio(
      displayName: 'Ivica Zubac',
      jerseyNumber: '40',
      heightCm: 213.4,
      weightKg: 108.9,
      country: 'Croatia',
      previousTeam: 'Mega Basket',
      birthDate: DateTime(1997, 3, 18),
      experienceYears: 9,
    ),
    'ja morant': PlayerBio(
      displayName: 'Ja Morant',
      jerseyNumber: '12',
      heightCm: 188,
      weightKg: 78.9,
      country: 'USA',
      previousTeam: 'Murray State',
      birthDate: DateTime(1999, 8, 10),
      experienceYears: 6,
    ),
    'jabari smith jr': PlayerBio(
      displayName: 'Jabari Smith Jr.',
      jerseyNumber: '10',
      heightCm: 208.3,
      weightKg: 99.8,
      country: 'USA',
      previousTeam: 'Auburn',
      birthDate: DateTime(2003, 5, 13),
      experienceYears: 3,
    ),
    'jaden ivey': PlayerBio(
      displayName: 'Jaden Ivey',
      jerseyNumber: '23',
      heightCm: 193,
      weightKg: 88.5,
      country: 'USA',
      previousTeam: 'Purdue',
      birthDate: DateTime(2002, 2, 13),
      experienceYears: 3,
    ),
    'jaden mcdaniels': PlayerBio(
      displayName: 'Jaden McDaniels',
      jerseyNumber: '3',
      heightCm: 205.7,
      weightKg: 83.9,
      country: 'USA',
      previousTeam: 'Washington',
      birthDate: DateTime(2000, 9, 29),
      experienceYears: 5,
    ),
    'jaime jaquez jr': PlayerBio(
      displayName: 'Jaime Jaquez Jr.',
      jerseyNumber: '11',
      heightCm: 198.1,
      weightKg: 102.1,
      country: 'USA',
      previousTeam: 'UCLA',
      birthDate: DateTime(2001, 2, 18),
      experienceYears: 2,
    ),
    'jakob poeltl': PlayerBio(
      displayName: 'Jakob Poeltl',
      jerseyNumber: '19',
      heightCm: 213.4,
      weightKg: 117.9,
      country: 'Austria',
      previousTeam: 'Utah',
      birthDate: DateTime(1995, 10, 15),
      experienceYears: 9,
    ),
    'jalen brunson': PlayerBio(
      displayName: 'Jalen Brunson',
      jerseyNumber: '11',
      heightCm: 188,
      weightKg: 86.2,
      country: 'USA',
      previousTeam: 'Villanova',
      birthDate: DateTime(1996, 8, 31),
      experienceYears: 7,
    ),
    'jalen duren': PlayerBio(
      displayName: 'Jalen Duren',
      jerseyNumber: '0',
      heightCm: 208.3,
      weightKg: 113.4,
      country: 'USA',
      previousTeam: 'Memphis',
      birthDate: DateTime(2003, 11, 18),
      experienceYears: 3,
    ),
    'jalen green': PlayerBio(
      displayName: 'Jalen Green',
      jerseyNumber: '4',
      heightCm: 193,
      weightKg: 84.4,
      country: 'USA',
      previousTeam: 'NBA G League Ignite',
      birthDate: DateTime(2002, 2, 9),
      experienceYears: 4,
    ),
    'jalen johnson': PlayerBio(
      displayName: 'Jalen Johnson',
      jerseyNumber: '1',
      heightCm: 203.2,
      weightKg: 99.3,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(2001, 12, 18),
      experienceYears: 4,
    ),
    'jalen suggs': PlayerBio(
      displayName: 'Jalen Suggs',
      jerseyNumber: '4',
      heightCm: 195.6,
      weightKg: 93,
      country: 'USA',
      previousTeam: 'Gonzaga',
      birthDate: DateTime(2001, 6, 3),
      experienceYears: 4,
    ),
    'jalen williams': PlayerBio(
      displayName: 'Jalen Williams',
      jerseyNumber: '8',
      heightCm: 195.6,
      weightKg: 95.7,
      country: 'USA',
      previousTeam: 'Santa Clara',
      birthDate: DateTime(2001, 4, 14),
      experienceYears: 3,
    ),
    'jamal murray': PlayerBio(
      displayName: 'Jamal Murray',
      jerseyNumber: '27',
      heightCm: 193,
      weightKg: 97.5,
      country: 'Canada',
      previousTeam: 'Kentucky',
      birthDate: DateTime(1997, 2, 23),
      experienceYears: 9,
    ),
    'james harden': PlayerBio(
      displayName: 'James Harden',
      jerseyNumber: '1',
      heightCm: 195.6,
      weightKg: 99.8,
      country: 'USA',
      previousTeam: 'Arizona State',
      birthDate: DateTime(1989, 8, 26),
      experienceYears: 16,
    ),
    'jared mccain': PlayerBio(
      displayName: 'Jared McCain',
      jerseyNumber: '20',
      heightCm: 190.5,
      weightKg: 88.5,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(2004, 2, 20),
      experienceYears: 1,
    ),
    'jaren jackson jr': PlayerBio(
      displayName: 'Jaren Jackson Jr.',
      jerseyNumber: '8',
      heightCm: 208.3,
      weightKg: 109.8,
      country: 'USA',
      previousTeam: 'Michigan State',
      birthDate: DateTime(1999, 9, 15),
      experienceYears: 7,
    ),
    'jarred vanderbilt': PlayerBio(
      displayName: 'Jarred Vanderbilt',
      jerseyNumber: '2',
      heightCm: 203.2,
      weightKg: 97.1,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(1999, 4, 3),
      experienceYears: 7,
    ),
    'jarrett allen': PlayerBio(
      displayName: 'Jarrett Allen',
      jerseyNumber: '31',
      heightCm: 205.7,
      weightKg: 110.2,
      country: 'USA',
      previousTeam: 'Texas',
      birthDate: DateTime(1998, 4, 21),
      experienceYears: 8,
    ),
    'jaylen brown': PlayerBio(
      displayName: 'Jaylen Brown',
      jerseyNumber: '7',
      heightCm: 198.1,
      weightKg: 101.2,
      country: 'USA',
      previousTeam: 'California',
      birthDate: DateTime(1996, 10, 24),
      experienceYears: 9,
    ),
    'jaylen wells': PlayerBio(
      displayName: 'Jaylen Wells',
      jerseyNumber: '0',
      heightCm: 201,
      weightKg: 93,
      country: 'USA',
      previousTeam: 'Washington State',
      birthDate: DateTime(2003, 8, 26),
      experienceYears: 1,
    ),
    'jayson tatum': PlayerBio(
      displayName: 'Jayson Tatum',
      jerseyNumber: '0',
      heightCm: 203.2,
      weightKg: 95.3,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(1998, 3, 3),
      experienceYears: 8,
    ),
    'jerami grant': PlayerBio(
      displayName: 'Jerami Grant',
      jerseyNumber: '9',
      heightCm: 200.7,
      weightKg: 95.3,
      country: 'USA',
      previousTeam: 'Syracuse',
      birthDate: DateTime(1994, 3, 12),
      experienceYears: 11,
    ),
    'jeremy sochan': PlayerBio(
      displayName: 'Jeremy Sochan',
      jerseyNumber: '10',
      heightCm: 203.2,
      weightKg: 104.3,
      country: 'Poland',
      previousTeam: 'Baylor',
      birthDate: DateTime(2003, 5, 20),
      experienceYears: 3,
    ),
    'jimmy butler': PlayerBio(
      displayName: 'Jimmy Butler III',
      jerseyNumber: '10',
      heightCm: 200.7,
      weightKg: 104.3,
      country: 'USA',
      previousTeam: 'Marquette',
      birthDate: DateTime(1989, 9, 14),
      experienceYears: 14,
    ),
    'joel embiid': PlayerBio(
      displayName: 'Joel Embiid',
      jerseyNumber: '21',
      heightCm: 213.4,
      weightKg: 127,
      country: 'Cameroon',
      previousTeam: 'Kansas',
      birthDate: DateTime(1994, 3, 16),
      experienceYears: 9,
    ),
    'john collins': PlayerBio(
      displayName: 'John Collins',
      jerseyNumber: '20',
      heightCm: 205.7,
      weightKg: 102.5,
      country: 'USA',
      previousTeam: 'Wake Forest',
      birthDate: DateTime(1997, 9, 23),
      experienceYears: 8,
    ),
    'jonathan isaac': PlayerBio(
      displayName: 'Jonathan Isaac',
      jerseyNumber: '1',
      heightCm: 208.3,
      weightKg: 104.3,
      country: 'USA',
      previousTeam: 'Florida State',
      birthDate: DateTime(1997, 10, 3),
      experienceYears: 8,
    ),
    'jonathan kuminga': PlayerBio(
      displayName: 'Jonathan Kuminga',
      jerseyNumber: '00',
      heightCm: 200.7,
      weightKg: 102.1,
      country: 'DRC',
      previousTeam: 'NBA G League Ignite',
      birthDate: DateTime(2002, 10, 6),
      experienceYears: 4,
    ),
    'jonathan mogbo': PlayerBio(
      displayName: 'Jonathan Mogbo',
      jerseyNumber: '2',
      heightCm: 205.7,
      weightKg: 102.1,
      country: 'USA',
      previousTeam: 'San Francisco',
      birthDate: DateTime(2001, 10, 29),
      experienceYears: 1,
    ),
    'jordan clarkson': PlayerBio(
      displayName: 'Jordan Clarkson',
      jerseyNumber: '00',
      heightCm: 190.5,
      weightKg: 88,
      country: 'USA',
      previousTeam: 'Missouri',
      birthDate: DateTime(1992, 6, 7),
      experienceYears: 11,
    ),
    'jordan poole': PlayerBio(
      displayName: 'Jordan Poole',
      jerseyNumber: '13',
      heightCm: 193,
      weightKg: 88,
      country: 'USA',
      previousTeam: 'Michigan',
      birthDate: DateTime(1999, 6, 19),
      experienceYears: 6,
    ),
    'jose alvarado': PlayerBio(
      displayName: 'Jose Alvarado',
      jerseyNumber: '15',
      heightCm: 182.9,
      weightKg: 81.2,
      country: 'USA',
      previousTeam: 'Georgia Tech',
      birthDate: DateTime(1998, 4, 12),
      experienceYears: 4,
    ),
    'josh giddey': PlayerBio(
      displayName: 'Josh Giddey',
      jerseyNumber: '3',
      heightCm: 203.2,
      weightKg: 98,
      country: 'Australia',
      previousTeam: 'NBA Global Academy',
      birthDate: DateTime(2002, 10, 10),
      experienceYears: 4,
    ),
    'josh hart': PlayerBio(
      displayName: 'Josh Hart',
      jerseyNumber: '3',
      heightCm: 193,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'Villanova',
      birthDate: DateTime(1995, 3, 6),
      experienceYears: 8,
    ),
    'jrue holiday': PlayerBio(
      displayName: 'Jrue Holiday',
      jerseyNumber: '5',
      heightCm: 193,
      weightKg: 93,
      country: 'USA',
      previousTeam: 'UCLA',
      birthDate: DateTime(1990, 6, 12),
      experienceYears: 16,
    ),
    'julius randle': PlayerBio(
      displayName: 'Julius Randle',
      jerseyNumber: '30',
      heightCm: 205.7,
      weightKg: 113.4,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(1994, 11, 29),
      experienceYears: 11,
    ),
    'karl anthony towns': PlayerBio(
      displayName: 'Karl-Anthony Towns',
      jerseyNumber: '32',
      heightCm: 213.4,
      weightKg: 112.5,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(1995, 11, 15),
      experienceYears: 10,
    ),
    'kawhi leonard': PlayerBio(
      displayName: 'Kawhi Leonard',
      jerseyNumber: '2',
      heightCm: 200.7,
      weightKg: 102.1,
      country: 'USA',
      previousTeam: 'San Diego State',
      birthDate: DateTime(1991, 6, 29),
      experienceYears: 14,
    ),
    'keegan murray': PlayerBio(
      displayName: 'Keegan Murray',
      jerseyNumber: '13',
      heightCm: 203.2,
      weightKg: 102.1,
      country: 'USA',
      previousTeam: 'Iowa',
      birthDate: DateTime(2000, 8, 19),
      experienceYears: 3,
    ),
    'kel el ware': PlayerBio(
      displayName: 'Kel\'el Ware',
      jerseyNumber: '7',
      heightCm: 213.4,
      weightKg: 104.3,
      country: 'USA',
      previousTeam: 'Indiana',
      birthDate: DateTime(2004, 4, 20),
      experienceYears: 1,
    ),
    'keldon johnson': PlayerBio(
      displayName: 'Keldon Johnson',
      jerseyNumber: '0',
      heightCm: 195.6,
      weightKg: 99.8,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(1999, 10, 11),
      experienceYears: 6,
    ),
    'kelly oubre jr': PlayerBio(
      displayName: 'Kelly Oubre Jr.',
      jerseyNumber: '9',
      heightCm: 203.2,
      weightKg: 92.1,
      country: 'USA',
      previousTeam: 'Kansas',
      birthDate: DateTime(1995, 12, 9),
      experienceYears: 10,
    ),
    'kentavious caldwell pope': PlayerBio(
      displayName: 'Kentavious Caldwell-Pope',
      jerseyNumber: '3',
      heightCm: 195.6,
      weightKg: 92.5,
      country: 'USA',
      previousTeam: 'Georgia',
      birthDate: DateTime(1993, 2, 18),
      experienceYears: 12,
    ),
    'kevin durant': PlayerBio(
      displayName: 'Kevin Durant',
      jerseyNumber: '7',
      heightCm: 210.8,
      weightKg: 108.9,
      country: 'USA',
      previousTeam: 'Texas',
      birthDate: DateTime(1988, 9, 29),
      experienceYears: 18,
    ),
    'kevin porter jr': PlayerBio(
      displayName: 'Kevin Porter Jr.',
      jerseyNumber: '3',
      heightCm: 193,
      weightKg: 92.1,
      country: 'USA',
      previousTeam: 'Southern California',
      birthDate: DateTime(2000, 5, 4),
      experienceYears: 5,
    ),
    'keyonte george': PlayerBio(
      displayName: 'Keyonte George',
      jerseyNumber: '3',
      heightCm: 193,
      weightKg: 83.9,
      country: 'USA',
      previousTeam: 'Baylor',
      birthDate: DateTime(2003, 11, 8),
      experienceYears: 2,
    ),
    'khris middleton': PlayerBio(
      displayName: 'Khris Middleton',
      jerseyNumber: '32',
      heightCm: 200.7,
      weightKg: 100.7,
      country: 'USA',
      previousTeam: 'Texas A\u0026M',
      birthDate: DateTime(1991, 8, 12),
      experienceYears: 13,
    ),
    'klay thompson': PlayerBio(
      displayName: 'Klay Thompson',
      jerseyNumber: '31',
      heightCm: 195.6,
      weightKg: 99.8,
      country: 'USA',
      previousTeam: 'Washington State',
      birthDate: DateTime(1990, 2, 8),
      experienceYears: 14,
    ),
    'kon knueppel': PlayerBio(
      displayName: 'Kon Knueppel',
      jerseyNumber: '7',
      heightCm: 195.6,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(2005, 8, 3),
      experienceYears: 0,
    ),
    'kristaps porzingis': PlayerBio(
      displayName: 'Kristaps Porzingis',
      jerseyNumber: '8',
      heightCm: 218,
      weightKg: 109,
      country: 'Latvia',
      previousTeam: 'Sevilla',
      birthDate: DateTime(1995, 8, 2),
      experienceYears: 10,
    ),
    'kyle kuzma': PlayerBio(
      displayName: 'Kyle Kuzma',
      jerseyNumber: '18',
      heightCm: 205.7,
      weightKg: 100.2,
      country: 'USA',
      previousTeam: 'Utah',
      birthDate: DateTime(1995, 7, 24),
      experienceYears: 8,
    ),
    'kyrie irving': PlayerBio(
      displayName: 'Kyrie Irving',
      jerseyNumber: '11',
      heightCm: 188,
      weightKg: 88.5,
      country: 'Australia',
      previousTeam: 'Duke',
      birthDate: DateTime(1992, 3, 23),
      experienceYears: 14,
    ),
    'kyshawn george': PlayerBio(
      displayName: 'Kyshawn George',
      jerseyNumber: '18',
      heightCm: 203.2,
      weightKg: 90.7,
      country: 'Switzerland',
      previousTeam: 'Miami',
      birthDate: DateTime(2003, 12, 12),
      experienceYears: 1,
    ),
    'lamelo ball': PlayerBio(
      displayName: 'LaMelo Ball',
      jerseyNumber: '1',
      heightCm: 200.7,
      weightKg: 81.6,
      country: 'USA',
      previousTeam: 'Illawarra',
      birthDate: DateTime(2001, 8, 22),
      experienceYears: 5,
    ),
    'lauri markkanen': PlayerBio(
      displayName: 'Lauri Markkanen',
      jerseyNumber: '23',
      heightCm: 213.4,
      weightKg: 108.9,
      country: 'Finland',
      previousTeam: 'Arizona',
      birthDate: DateTime(1997, 5, 22),
      experienceYears: 8,
    ),
    'lebron james': PlayerBio(
      displayName: 'LeBron James',
      jerseyNumber: '23',
      heightCm: 205.7,
      weightKg: 113.4,
      country: 'USA',
      previousTeam: 'St. Vincent-St. Mary HS (OH)',
      birthDate: DateTime(1984, 12, 30),
      experienceYears: 22,
    ),
    'luguentz dort': PlayerBio(
      displayName: 'Luguentz Dort',
      jerseyNumber: '5',
      heightCm: 193,
      weightKg: 99.8,
      country: 'Canada',
      previousTeam: 'Arizona State',
      birthDate: DateTime(1999, 4, 19),
      experienceYears: 6,
    ),
    'luka doncic': PlayerBio(
      displayName: 'Luka Doncic',
      jerseyNumber: '77',
      heightCm: 198,
      weightKg: 104,
      country: 'Slovenia',
      previousTeam: 'Real Madrid',
      birthDate: DateTime(1999, 2, 28),
      experienceYears: 7,
    ),
    'luke kennard': PlayerBio(
      displayName: 'Luke Kennard',
      jerseyNumber: '10',
      heightCm: 195.6,
      weightKg: 93.4,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(1996, 6, 24),
      experienceYears: 8,
    ),
    'malik monk': PlayerBio(
      displayName: 'Malik Monk',
      jerseyNumber: '0',
      heightCm: 190.5,
      weightKg: 90.7,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(1998, 2, 4),
      experienceYears: 8,
    ),
    'marcus smart': PlayerBio(
      displayName: 'Marcus Smart',
      jerseyNumber: '36',
      heightCm: 193,
      weightKg: 100,
      country: 'USA',
      previousTeam: 'Oklahoma State',
      birthDate: DateTime(1994, 3, 6),
      experienceYears: 11,
    ),
    'mark williams': PlayerBio(
      displayName: 'Mark Williams',
      jerseyNumber: '5',
      heightCm: 213.4,
      weightKg: 108.9,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(2001, 12, 16),
      experienceYears: 3,
    ),
    'matas buzelis': PlayerBio(
      displayName: 'Matas Buzelis',
      jerseyNumber: '14',
      heightCm: 208.3,
      weightKg: 94.8,
      country: 'USA',
      previousTeam: 'NBA G League Ignite',
      birthDate: DateTime(2004, 10, 13),
      experienceYears: 1,
    ),
    'max christie': PlayerBio(
      displayName: 'Max Christie',
      jerseyNumber: '00',
      heightCm: 195.6,
      weightKg: 86.2,
      country: 'USA',
      previousTeam: 'Michigan State',
      birthDate: DateTime(2003, 2, 10),
      experienceYears: 3,
    ),
    'max strus': PlayerBio(
      displayName: 'Max Strus',
      jerseyNumber: '1',
      heightCm: 195.6,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'DePaul',
      birthDate: DateTime(1996, 3, 28),
      experienceYears: 6,
    ),
    'michael porter jr': PlayerBio(
      displayName: 'Michael Porter Jr.',
      jerseyNumber: '7',
      heightCm: 208.3,
      weightKg: 98.9,
      country: 'USA',
      previousTeam: 'Missouri',
      birthDate: DateTime(1998, 6, 29),
      experienceYears: 6,
    ),
    'mikal bridges': PlayerBio(
      displayName: 'Mikal Bridges',
      jerseyNumber: '25',
      heightCm: 198.1,
      weightKg: 94.8,
      country: 'USA',
      previousTeam: 'Villanova',
      birthDate: DateTime(1996, 8, 30),
      experienceYears: 7,
    ),
    'mike conley': PlayerBio(
      displayName: 'Mike Conley',
      jerseyNumber: '10',
      heightCm: 182.9,
      weightKg: 79.4,
      country: 'USA',
      previousTeam: 'Ohio State',
      birthDate: DateTime(1987, 10, 11),
      experienceYears: 18,
    ),
    'miles bridges': PlayerBio(
      displayName: 'Miles Bridges',
      jerseyNumber: '0',
      heightCm: 200.7,
      weightKg: 102.1,
      country: 'USA',
      previousTeam: 'Michigan State',
      birthDate: DateTime(1998, 3, 21),
      experienceYears: 6,
    ),
    'miles mcbride': PlayerBio(
      displayName: 'Miles McBride',
      jerseyNumber: '2',
      heightCm: 185.4,
      weightKg: 88.5,
      country: 'USA',
      previousTeam: 'West Virginia',
      birthDate: DateTime(2000, 9, 8),
      experienceYears: 4,
    ),
    'mitchell robinson': PlayerBio(
      displayName: 'Mitchell Robinson',
      jerseyNumber: '23',
      heightCm: 213.4,
      weightKg: 108.9,
      country: 'USA',
      previousTeam: 'Western Kentucky',
      birthDate: DateTime(1998, 4, 1),
      experienceYears: 7,
    ),
    'moussa diabate': PlayerBio(
      displayName: 'Moussa Diabate',
      jerseyNumber: '14',
      heightCm: 208,
      weightKg: 95,
      country: 'France',
      previousTeam: 'Michigan',
      birthDate: DateTime(2002, 1, 21),
      experienceYears: 3,
    ),
    'myles turner': PlayerBio(
      displayName: 'Myles Turner',
      jerseyNumber: '33',
      heightCm: 210.8,
      weightKg: 113.4,
      country: 'USA',
      previousTeam: 'Texas',
      birthDate: DateTime(1996, 3, 24),
      experienceYears: 10,
    ),
    'naz reid': PlayerBio(
      displayName: 'Naz Reid',
      jerseyNumber: '11',
      heightCm: 205.7,
      weightKg: 119.7,
      country: 'USA',
      previousTeam: 'Louisiana State',
      birthDate: DateTime(1999, 8, 26),
      experienceYears: 6,
    ),
    'neemias queta': PlayerBio(
      displayName: 'Neemias Queta',
      jerseyNumber: '88',
      heightCm: 213.4,
      weightKg: 112.5,
      country: 'Portugal',
      previousTeam: 'Utah State',
      birthDate: DateTime(1999, 7, 13),
      experienceYears: 4,
    ),
    'nic claxton': PlayerBio(
      displayName: 'Nic Claxton',
      jerseyNumber: '33',
      heightCm: 210.8,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'Georgia',
      birthDate: DateTime(1999, 4, 17),
      experienceYears: 6,
    ),
    'nick richards': PlayerBio(
      displayName: 'Nick Richards',
      jerseyNumber: '2',
      heightCm: 213.4,
      weightKg: 111.1,
      country: 'Jamaica',
      previousTeam: 'Kentucky',
      birthDate: DateTime(1997, 11, 29),
      experienceYears: 5,
    ),
    'nickeil alexander walker': PlayerBio(
      displayName: 'Nickeil Alexander-Walker',
      jerseyNumber: '7',
      heightCm: 195.6,
      weightKg: 93,
      country: 'Canada',
      previousTeam: 'Virginia Tech',
      birthDate: DateTime(1998, 9, 2),
      experienceYears: 6,
    ),
    'nikola jokic': PlayerBio(
      displayName: 'Nikola Jokic',
      jerseyNumber: '15',
      heightCm: 211,
      weightKg: 129,
      country: 'Serbia',
      previousTeam: 'Mega Basket',
      birthDate: DateTime(1995, 2, 19),
      experienceYears: 10,
    ),
    'nikola vucevic': PlayerBio(
      displayName: 'Nikola Vucevic',
      jerseyNumber: '9',
      heightCm: 208,
      weightKg: 118,
      country: 'Montenegro',
      previousTeam: 'USC',
      birthDate: DateTime(1990, 10, 24),
      experienceYears: 14,
    ),
    'noah clowney': PlayerBio(
      displayName: 'Noah Clowney',
      jerseyNumber: '21',
      heightCm: 205.7,
      weightKg: 95.3,
      country: 'USA',
      previousTeam: 'Alabama',
      birthDate: DateTime(2004, 7, 14),
      experienceYears: 2,
    ),
    'norman powell': PlayerBio(
      displayName: 'Norman Powell',
      jerseyNumber: '24',
      heightCm: 193,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'UCLA',
      birthDate: DateTime(1993, 5, 25),
      experienceYears: 10,
    ),
    'obi toppin': PlayerBio(
      displayName: 'Obi Toppin',
      jerseyNumber: '1',
      heightCm: 205.7,
      weightKg: 99.8,
      country: 'USA',
      previousTeam: 'Dayton',
      birthDate: DateTime(1998, 3, 4),
      experienceYears: 5,
    ),
    'ochai agbaji': PlayerBio(
      displayName: 'Ochai Agbaji',
      jerseyNumber: '30',
      heightCm: 195.6,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'Kansas',
      birthDate: DateTime(2000, 4, 20),
      experienceYears: 3,
    ),
    'og anunoby': PlayerBio(
      displayName: 'OG Anunoby',
      jerseyNumber: '8',
      heightCm: 200.7,
      weightKg: 108.9,
      country: 'United Kingdom',
      previousTeam: 'Indiana',
      birthDate: DateTime(1997, 7, 17),
      experienceYears: 8,
    ),
    'onyeka okongwu': PlayerBio(
      displayName: 'Onyeka Okongwu',
      jerseyNumber: '17',
      heightCm: 208.3,
      weightKg: 108.9,
      country: 'USA',
      previousTeam: 'Southern California',
      birthDate: DateTime(2000, 12, 11),
      experienceYears: 5,
    ),
    'paolo banchero': PlayerBio(
      displayName: 'Paolo Banchero',
      jerseyNumber: '5',
      heightCm: 208.3,
      weightKg: 113.4,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(2002, 11, 12),
      experienceYears: 3,
    ),
    'pascal siakam': PlayerBio(
      displayName: 'Pascal Siakam',
      jerseyNumber: '43',
      heightCm: 203.2,
      weightKg: 111.1,
      country: 'Cameroon',
      previousTeam: 'New Mexico State',
      birthDate: DateTime(1994, 4, 2),
      experienceYears: 9,
    ),
    'patrick williams': PlayerBio(
      displayName: 'Patrick Williams',
      jerseyNumber: '44',
      heightCm: 200.7,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'Florida State',
      birthDate: DateTime(2001, 8, 26),
      experienceYears: 5,
    ),
    'paul george': PlayerBio(
      displayName: 'Paul George',
      jerseyNumber: '8',
      heightCm: 203.2,
      weightKg: 99.8,
      country: 'USA',
      previousTeam: 'Fresno State',
      birthDate: DateTime(1990, 5, 2),
      experienceYears: 15,
    ),
    'payton pritchard': PlayerBio(
      displayName: 'Payton Pritchard',
      jerseyNumber: '11',
      heightCm: 185.4,
      weightKg: 88.5,
      country: 'USA',
      previousTeam: 'Oregon',
      birthDate: DateTime(1998, 1, 28),
      experienceYears: 5,
    ),
    'peyton watson': PlayerBio(
      displayName: 'Peyton Watson',
      jerseyNumber: '8',
      heightCm: 200.7,
      weightKg: 90.7,
      country: 'USA',
      previousTeam: 'UCLA',
      birthDate: DateTime(2002, 9, 11),
      experienceYears: 3,
    ),
    'pj washington': PlayerBio(
      displayName: 'P.J. Washington',
      jerseyNumber: '25',
      heightCm: 198.1,
      weightKg: 104.3,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(1998, 8, 23),
      experienceYears: 6,
    ),
    'precious achiuwa': PlayerBio(
      displayName: 'Precious Achiuwa',
      jerseyNumber: '5',
      heightCm: 203.2,
      weightKg: 110.2,
      country: 'Nigeria',
      previousTeam: 'Memphis',
      birthDate: DateTime(1999, 9, 19),
      experienceYears: 5,
    ),
    'quentin grimes': PlayerBio(
      displayName: 'Quentin Grimes',
      jerseyNumber: '5',
      heightCm: 193,
      weightKg: 95.3,
      country: 'USA',
      previousTeam: 'Houston',
      birthDate: DateTime(2000, 5, 8),
      experienceYears: 4,
    ),
    'reed sheppard': PlayerBio(
      displayName: 'Reed Sheppard',
      jerseyNumber: '15',
      heightCm: 188,
      weightKg: 83.9,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(2004, 6, 24),
      experienceYears: 1,
    ),
    'rj barrett': PlayerBio(
      displayName: 'RJ Barrett',
      jerseyNumber: '9',
      heightCm: 198.1,
      weightKg: 97.1,
      country: 'Canada',
      previousTeam: 'Duke',
      birthDate: DateTime(2000, 6, 14),
      experienceYears: 6,
    ),
    'rob dillingham': PlayerBio(
      displayName: 'Rob Dillingham',
      jerseyNumber: '4',
      heightCm: 190.5,
      weightKg: 79.4,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(2005, 1, 4),
      experienceYears: 1,
    ),
    'robert williams iii': PlayerBio(
      displayName: 'Robert Williams III',
      jerseyNumber: '35',
      heightCm: 205.7,
      weightKg: 112.9,
      country: 'USA',
      previousTeam: 'Texas A\u0026M',
      birthDate: DateTime(1997, 10, 17),
      experienceYears: 7,
    ),
    'ron holland': PlayerBio(
      displayName: 'Ronald Holland II',
      jerseyNumber: '5',
      heightCm: 203.2,
      weightKg: 93.4,
      country: 'USA',
      previousTeam: 'NBA G League Ignite',
      birthDate: DateTime(2005, 7, 7),
      experienceYears: 1,
    ),
    'royce oneale': PlayerBio(
      displayName: 'Royce ONeale',
      jerseyNumber: '00',
      heightCm: 193,
      weightKg: 103,
      country: 'USA',
      previousTeam: 'Baylor',
      birthDate: DateTime(1993, 6, 5),
      experienceYears: 8,
    ),
    'rudy gobert': PlayerBio(
      displayName: 'Rudy Gobert',
      jerseyNumber: '27',
      heightCm: 215.9,
      weightKg: 117,
      country: 'France',
      previousTeam: 'Cholet',
      birthDate: DateTime(1992, 6, 26),
      experienceYears: 12,
    ),
    'rui hachimura': PlayerBio(
      displayName: 'Rui Hachimura',
      jerseyNumber: '28',
      heightCm: 203.2,
      weightKg: 104.3,
      country: 'Japan',
      previousTeam: 'Gonzaga',
      birthDate: DateTime(1998, 2, 8),
      experienceYears: 6,
    ),
    'russell westbrook': PlayerBio(
      displayName: 'Russell Westbrook',
      jerseyNumber: '4',
      heightCm: 193,
      weightKg: 90.7,
      country: 'USA',
      previousTeam: 'UCLA',
      birthDate: DateTime(1988, 11, 12),
      experienceYears: 17,
    ),
    'ryan dunn': PlayerBio(
      displayName: 'Ryan Dunn',
      jerseyNumber: '0',
      heightCm: 203.2,
      weightKg: 98,
      country: 'USA',
      previousTeam: 'Virginia',
      birthDate: DateTime(2003, 1, 7),
      experienceYears: 1,
    ),
    'saddiq bey': PlayerBio(
      displayName: 'Saddiq Bey',
      jerseyNumber: '14',
      heightCm: 200.7,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'Villanova',
      birthDate: DateTime(1999, 4, 9),
      experienceYears: 5,
    ),
    'sam hauser': PlayerBio(
      displayName: 'Sam Hauser',
      jerseyNumber: '30',
      heightCm: 200.7,
      weightKg: 98.4,
      country: 'USA',
      previousTeam: 'Virginia',
      birthDate: DateTime(1997, 12, 8),
      experienceYears: 4,
    ),
    'sam merrill': PlayerBio(
      displayName: 'Sam Merrill',
      jerseyNumber: '5',
      heightCm: 193,
      weightKg: 93,
      country: 'USA',
      previousTeam: 'Utah State',
      birthDate: DateTime(1996, 5, 15),
      experienceYears: 5,
    ),
    'santi aldama': PlayerBio(
      displayName: 'Santi Aldama',
      jerseyNumber: '7',
      heightCm: 213.4,
      weightKg: 97.5,
      country: 'Spain',
      previousTeam: 'Loyola-Maryland',
      birthDate: DateTime(2001, 1, 10),
      experienceYears: 4,
    ),
    'scoot henderson': PlayerBio(
      displayName: 'Scoot Henderson',
      jerseyNumber: '00',
      heightCm: 190.5,
      weightKg: 93.4,
      country: 'USA',
      previousTeam: 'NBA G League Ignite',
      birthDate: DateTime(2004, 2, 3),
      experienceYears: 2,
    ),
    'scottie barnes': PlayerBio(
      displayName: 'Scottie Barnes',
      jerseyNumber: '4',
      heightCm: 200.7,
      weightKg: 107.5,
      country: 'USA',
      previousTeam: 'Florida State',
      birthDate: DateTime(2001, 8, 1),
      experienceYears: 4,
    ),
    'shaedon sharpe': PlayerBio(
      displayName: 'Shaedon Sharpe',
      jerseyNumber: '17',
      heightCm: 195.6,
      weightKg: 94.3,
      country: 'Canada',
      previousTeam: 'Kentucky',
      birthDate: DateTime(2003, 5, 30),
      experienceYears: 3,
    ),
    'shai gilgeous alexander': PlayerBio(
      displayName: 'Shai Gilgeous-Alexander',
      jerseyNumber: '2',
      heightCm: 198.1,
      weightKg: 88.5,
      country: 'Canada',
      previousTeam: 'Kentucky',
      birthDate: DateTime(1998, 7, 12),
      experienceYears: 7,
    ),
    'stephen curry': PlayerBio(
      displayName: 'Stephen Curry',
      jerseyNumber: '30',
      heightCm: 188,
      weightKg: 83.9,
      country: 'USA',
      previousTeam: 'Davidson',
      birthDate: DateTime(1988, 3, 14),
      experienceYears: 16,
    ),
    'stephon castle': PlayerBio(
      displayName: 'Stephon Castle',
      jerseyNumber: '5',
      heightCm: 198.1,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'Connecticut',
      birthDate: DateTime(2004, 11, 1),
      experienceYears: 1,
    ),
    'tari eason': PlayerBio(
      displayName: 'Tari Eason',
      jerseyNumber: '17',
      heightCm: 203.2,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'Louisiana State',
      birthDate: DateTime(2001, 5, 10),
      experienceYears: 3,
    ),
    'taurean prince': PlayerBio(
      displayName: 'Taurean Prince',
      jerseyNumber: '12',
      heightCm: 198.1,
      weightKg: 98.9,
      country: 'USA',
      previousTeam: 'Baylor',
      birthDate: DateTime(1994, 3, 22),
      experienceYears: 9,
    ),
    'taylor hendricks': PlayerBio(
      displayName: 'Taylor Hendricks',
      jerseyNumber: '0',
      heightCm: 205.7,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'Central Florida',
      birthDate: DateTime(2003, 11, 22),
      experienceYears: 2,
    ),
    'terance mann': PlayerBio(
      displayName: 'Terance Mann',
      jerseyNumber: '14',
      heightCm: 195.6,
      weightKg: 97.5,
      country: 'USA',
      previousTeam: 'Florida State',
      birthDate: DateTime(1996, 10, 18),
      experienceYears: 6,
    ),
    'terry rozier': PlayerBio(
      displayName: 'Terry Rozier',
      jerseyNumber: '2',
      heightCm: 185.4,
      weightKg: 86.2,
      country: 'USA',
      previousTeam: 'Louisville',
      birthDate: DateTime(1994, 3, 17),
      experienceYears: 11,
    ),
    'tj mcconnell': PlayerBio(
      displayName: 'T.J. McConnell',
      jerseyNumber: '9',
      heightCm: 185.4,
      weightKg: 86.2,
      country: 'USA',
      previousTeam: 'Arizona',
      birthDate: DateTime(1992, 3, 25),
      experienceYears: 10,
    ),
    'tobias harris': PlayerBio(
      displayName: 'Tobias Harris',
      jerseyNumber: '12',
      heightCm: 203.2,
      weightKg: 102.5,
      country: 'USA',
      previousTeam: 'Tennessee',
      birthDate: DateTime(1992, 7, 15),
      experienceYears: 14,
    ),
    'toumani camara': PlayerBio(
      displayName: 'Toumani Camara',
      jerseyNumber: '33',
      heightCm: 200.7,
      weightKg: 103.9,
      country: 'Belgium',
      previousTeam: 'Dayton',
      birthDate: DateTime(2000, 5, 8),
      experienceYears: 2,
    ),
    'trae young': PlayerBio(
      displayName: 'Trae Young',
      jerseyNumber: '11',
      heightCm: 185.4,
      weightKg: 74.4,
      country: 'USA',
      previousTeam: 'Oklahoma',
      birthDate: DateTime(1998, 9, 19),
      experienceYears: 7,
    ),
    'tre johnson': PlayerBio(
      displayName: 'Tre Johnson',
      jerseyNumber: '12',
      heightCm: 195.6,
      weightKg: 86.2,
      country: 'USA',
      previousTeam: 'Texas',
      birthDate: DateTime(2006, 3, 7),
      experienceYears: 0,
    ),
    'tre jones': PlayerBio(
      displayName: 'Tre Jones',
      jerseyNumber: '30',
      heightCm: 185.4,
      weightKg: 83.9,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(2000, 1, 8),
      experienceYears: 5,
    ),
    'tre mann': PlayerBio(
      displayName: 'Tre Mann',
      jerseyNumber: '23',
      heightCm: 190.5,
      weightKg: 80.7,
      country: 'USA',
      previousTeam: 'Florida',
      birthDate: DateTime(2001, 2, 3),
      experienceYears: 4,
    ),
    'trey murphy iii': PlayerBio(
      displayName: 'Trey Murphy III',
      jerseyNumber: '25',
      heightCm: 203.2,
      weightKg: 93.4,
      country: 'USA',
      previousTeam: 'Virginia',
      birthDate: DateTime(2000, 6, 18),
      experienceYears: 4,
    ),
    'tyler herro': PlayerBio(
      displayName: 'Tyler Herro',
      jerseyNumber: '14',
      heightCm: 195.6,
      weightKg: 88.5,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(2000, 1, 20),
      experienceYears: 6,
    ),
    'tyrese haliburton': PlayerBio(
      displayName: 'Tyrese Haliburton',
      jerseyNumber: '0',
      heightCm: 195.6,
      weightKg: 83.9,
      country: 'USA',
      previousTeam: 'Iowa State',
      birthDate: DateTime(2000, 2, 29),
      experienceYears: 5,
    ),
    'tyrese maxey': PlayerBio(
      displayName: 'Tyrese Maxey',
      jerseyNumber: '0',
      heightCm: 188,
      weightKg: 90.7,
      country: 'USA',
      previousTeam: 'Kentucky',
      birthDate: DateTime(2000, 11, 4),
      experienceYears: 5,
    ),
    'victor wembanyama': PlayerBio(
      displayName: 'Victor Wembanyama',
      jerseyNumber: '1',
      heightCm: 221,
      weightKg: 106.6,
      country: 'France',
      previousTeam: 'Metropolitans 92',
      birthDate: DateTime(2004, 1, 4),
      experienceYears: 2,
    ),
    'vj edgecombe': PlayerBio(
      displayName: 'VJ Edgecombe',
      heightCm: 201,
      weightKg: 82,
      country: 'Bahamas',
      previousTeam: 'Baylor',
      birthDate: DateTime(2005, 7, 30),
      experienceYears: 0,
    ),
    'walker kessler': PlayerBio(
      displayName: 'Walker Kessler',
      jerseyNumber: '24',
      heightCm: 213.4,
      weightKg: 111.1,
      country: 'USA',
      previousTeam: 'Auburn',
      birthDate: DateTime(2001, 7, 26),
      experienceYears: 3,
    ),
    'wendell carter jr': PlayerBio(
      displayName: 'Wendell Carter Jr.',
      jerseyNumber: '34',
      heightCm: 208.3,
      weightKg: 122.5,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(1999, 4, 16),
      experienceYears: 7,
    ),
    'xavier tillman': PlayerBio(
      displayName: 'Xavier Tillman',
      jerseyNumber: '26',
      heightCm: 200.7,
      weightKg: 111.1,
      country: 'USA',
      previousTeam: 'Michigan State',
      birthDate: DateTime(1999, 1, 12),
      experienceYears: 5,
    ),
    'yves missi': PlayerBio(
      displayName: 'Yves Missi',
      jerseyNumber: '21',
      heightCm: 210.8,
      weightKg: 106.6,
      country: 'Cameroon',
      previousTeam: 'Baylor',
      birthDate: DateTime(2004, 5, 14),
      experienceYears: 1,
    ),
    'zaccharie risacher': PlayerBio(
      displayName: 'Zaccharie Risacher',
      jerseyNumber: '10',
      heightCm: 203.2,
      weightKg: 90.7,
      country: 'France',
      previousTeam: 'JL Bourg-en-Bresse',
      birthDate: DateTime(2005, 4, 8),
      experienceYears: 1,
    ),
    'zach edey': PlayerBio(
      displayName: 'Zach Edey',
      jerseyNumber: '14',
      heightCm: 223.5,
      weightKg: 138.3,
      country: 'Canada',
      previousTeam: 'Purdue',
      birthDate: DateTime(2002, 5, 14),
      experienceYears: 1,
    ),
    'zach lavine': PlayerBio(
      displayName: 'Zach LaVine',
      jerseyNumber: '8',
      heightCm: 195.6,
      weightKg: 90.7,
      country: 'USA',
      previousTeam: 'UCLA',
      birthDate: DateTime(1995, 3, 10),
      experienceYears: 11,
    ),
    'zion williamson': PlayerBio(
      displayName: 'Zion Williamson',
      jerseyNumber: '1',
      heightCm: 198.1,
      weightKg: 128.8,
      country: 'USA',
      previousTeam: 'Duke',
      birthDate: DateTime(2000, 7, 6),
      experienceYears: 6,
    ),
  };

  static String normalizeName(String value) => value
      .toLowerCase()
      .replaceAll(RegExp(r'[^a-z0-9]+'), ' ')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();

  static PlayerBio? forName(String fullName) =>
      biosByName[normalizeName(fullName)];
}

class PlayerBio {
  final String? displayName;
  final String? jerseyNumber;
  final double? heightCm;
  final double? weightKg;
  final DateTime? birthDate;
  final String? country;
  final String? previousTeam;
  final int? experienceYears;

  const PlayerBio({
    this.displayName,
    this.jerseyNumber,
    this.heightCm,
    this.weightKg,
    this.birthDate,
    this.country,
    this.previousTeam,
    this.experienceYears,
  });
}
